### ISSUE TITLE
done usage of function different 

### ISSUE THREAD

**Issue by mhf-ir** [jonnyreeves/jquery-Mustache#1]
var viewData = { name: 'Jonny' };
this is not work:
$.Mustache.load('./templates/greetings.htm')
    .done(function () {
        $('body').mustache('simple-hello', viewData);
    });
});

but this worked:
$.Mustache.load('./templates/greetings.htm')
    .done(myfunction());
});

**Comment by jonnyreeves** [comment]
Hi, and thanks for your interest in the project. I can't immediately see what issue you are experiencing from your snippet above, please could you create a gist which demonstrates the problem? 

Thanks, 
Jonny 

_Sent via Hubroid_

**Comment by mhf-ir** [comment]
i get error:
No template registered for: xxxxxxxxxx

**Comment by jonnyreeves** [comment]
I'm happy to help, but I need you to upload your source files which demonstrate the issue. 

I am going to close this issue for now, but am happy to reopen it once you've done the above. 

Thanks 

_Sent via Hubroid_
