### ISSUE TITLE
window.Mustache is not set?

### ISSUE THREAD

**Issue by terrycojones** [jonnyreeves/jquery-Mustache#11]
Sorry for all the n00b comments...

I have some simple code that looks like this:

```
$(document).ready(function(){
    $.Mustache.load('templates.html', function(){
        console.log('templates loaded');
        init();
    });
});
```

The load works, and if I add a console.log in the add method I can see that my templates have been found correctly in the HTML template file.

However, when I later run `$('#my-id').mustache('my-template', {})` I get an error in the JS console:

```
Uncaught Error: Failed to locate Mustache instance, are you sure it has been loaded?
```

From what I can see, this is occurring because `getMustache` is looking for `window.Mustache` but it looks like that's never set.  Should it instead be `$.Mustache`?

I'm not completely sure what I'm doing here, so this might be pilot error...

**Comment by terrycojones** [comment]
OK, I figured it out :-)

If the error message was more explicit about what I forgot to do, that would be helpful. I'll submit a pull request. Sorry for the noise.

**Comment by Apocatastasis** [comment]
@terrycojones how do you resolve your problem?

**Comment by vacosk** [comment]
@terrycojones how did you solve it? Why its so difficult to post solution, when you found it. It's much better than just asking!

**Comment by pacid** [comment]
@Apocatastasis, @vacosk : 
Example I got working. I refer to $.Mustache as the Mustach object.

Here's a part of html:

``` javascript
...
<script src="http://cdnjs.cloudflare.com/ajax/libs/mustache.js/0.7.2/mustache.min.js"></script>
<script>
$(document).ready(function() {
        var person = {
            firstName: "Christophe",
            lastName: "Coenraets",
            blogURL: "http://coenraets.org"
        };
        var template = "<h1>{{firstName}} {{lastName}}</h1>Blog: {{blogURL}}";
        var html = $.Mustache.to_html(template, person);
});
</script>
```
