### ISSUE TITLE
addFromDom() only gets templates from the body

### ISSUE THREAD

**Issue by VinceG3** [jonnyreeves/jquery-Mustache#13]
The docs say the templates can be stored anywhere in the DOM and addFromDom() will get all of them, but they're only pulled from the body. Suggest clearer language in the documentation or changing the jquery selector to $("script") rather than $("body script").

**Comment by jonnyreeves** [comment]
Thanks for the tip!  I'm taking this oppertunity to add some test-coverage around the addFromDom() method whilst I'm at it :)

**Comment by jonnyreeves** [comment]
I've pushed this fix into the 0.2-dev branch - feel free to grab a copy from there if you need it before I merge for the next release (0.2.5)

**Comment by jonnyreeves** [comment]
This fix was merged into the 0.2.6 release.
