### ISSUE TITLE
addFromDom() doesn't work unless a template name is specified

### ISSUE THREAD

**Issue by bspingarn** [jonnyreeves/jquery-Mustache#14]
It seems addFromDom() isn't working for me unless I actually specify a template name. I have tried putting the template in both the HEAD tag and also the BODY tag-- it doesn't matter. The templates will only register if I actually pass in the name.

**Comment by jonnyreeves** [comment]
Hi there, have you seen the same issue in the 0.2-dev branch? (https://github.com/jonnyreeves/jquery-Mustache/tree/0.2-dev)  Let me know if that solves your issues.

Thanks, and have a great Christmas!

**Comment by bspingarn** [comment]
Sorry the delay on trying the 0.2v dev branch. It does not to appear to have fixed the issue. Templates still only load if I individually pass in their ID to addFromDom(). Let me know if theres anything else I can do to help troubleshoot.

**Comment by bspingarn** [comment]
Actually looks like an error on my part, my apologies. My templates had type="text/template" rather than "text/html".
