### ISSUE TITLE
options with " will not be parsed

### ISSUE THREAD

**Issue by jerryshen** [jonnyreeves/jquery-Mustache#2]
{"id":9 } doesn't work

{id: 9} works

but json result returns with "", how to make it work?

**Comment by jerryshen** [comment]
forget about it, it's my problem, I can handle this on the server side

**Comment by jonnyreeves** [comment]
Hi Jerry, I hope you've resolved your issue.  It doesn't sound like this problem is jquery-Mustache specific; but if you are trying to pass a JSON String as a ViewModel then you will need to call `JSON.parse` first, eg:

``` javascript
var viewModel = JSON.parse(jsonString);
```

**Comment by jerryshen** [comment]
yes, i have resolved it, I get the json data by jBuilder, it became a string,  when I got it in success return, it's not a object any more, so I tried to remove jBuilder, it's ok now, thanks for your awesome plugin
