### ISSUE TITLE
$("selector").mustache(template,data) should return jquery function for the new element

### ISSUE THREAD

**Issue by arieljake** [jonnyreeves/jquery-Mustache#20]
Doesn't it make more sense to return the newly created element when we call the mustache function?

**Comment by jonnyreeves** [comment]
`$(el).mustache()` currently returns a reference to `$(el)` to allow continued chaining.  This was chosen to remain consistent with jQuery's own API for method like `$(el).append(child)` which will return a reference to `$(el)`.
