### ISSUE TITLE
Load template file once and access templates in it several times

### ISSUE THREAD

**Issue by RaviRamDhali** [jonnyreeves/jquery-Mustache#23]
I am using the following code:

$.Mustache.load('/Scripts/CustomFormCreator/templates.html')
    .done(function () {
        $('#ControlGroupContainer').mustache('ControlGroupTemplate', controlGroup);
});

this is working great. However, I have about 4 templates within the 'templates.html' file.

I noticed that every time I call the $.Mustache.load, the file is loaded several times, which is expected.

What I wanted to do is load the 'template.html' ONCE and access all the templates with that file (from the DOM) as need.

// Load template file once (contains several defined templates)
$.Mustache.load('/Scripts/CustomFormCreator/templates.html').done();

// Load data and fill template
var html = Mustache.to_html('FirstTemplateFromLoadedFile', arrDataFoo);
$('#ArrayDataFooContainer').html(html);

And again 

// Load data and fill template
var html = Mustache.to_html('SecondTemplateFromLoadedFile', arrDataBar);
$('#ArrayDataBarContainer').html(html);

Thanks ..

**Comment by jonnyreeves** [comment]
Once a template has been loaded you can render it via `$.Mustache.render(templateName);`

**Comment by RaviRamDhali** [comment]
**WORKING CODE:**

On the initial page load:

```
$(document).ready(function () {
// load all templates into DOM from one template file
$.Mustache.load('/Scripts/CustomFormCreator/templates.html')
.done(function () {
            console.log("Templates loaded and ready to use!");
        });
});
```

then at the point where I need to Fill and Render the template:

```
// Get single template from DOM > Fill and Render
var html = $.Mustache.render('FirstTemplateFromLoadedFile', arrDataFoo);
$('#ArrayDataFooContainer').html(html);
```

then anywhere else I need to, I can render another template:

```

// Get single template from DOM > Fill and Render
var html = $.Mustache.render('SecondTemplateFromLoadedFile', arrDataBar);
$('#ArrayDataBarContainer').html(html);

```

**Comment by jonnyreeves** [comment]
Hi,

Glad this is working for you - it's worth noting that `$.Mustache.load()` is an asynchronous operation which only completes when the promise is 'done', eg:

```
$(document).ready(function () {
    $.Mustache.load('/Scripts/CustomFormCreator/templates.html')
        .done(function () {
            console.log("Templates loaded and ready to use!");
        });
});
```

I could add an option to ensure that templates files are only loaded once, but I'm worried this would bloat the API unnecessarily.

**Comment by RaviRamDhali** [comment]
Ahh .. got it. I updated my code above. Thanks again
