### ISSUE TITLE
expose 'has' function

### ISSUE THREAD

**Issue by arieljake** [jonnyreeves/jquery-Mustache#24]
currently has is not exposed in the $.Mustache public api, it would be handy to use

**Comment by jonnyreeves** [comment]
Hello, do you have a specific use case in mind?

**Comment by arieljake** [comment]
I am loading data from the server that optionally has a property 'templateId' corresponding to the mustache template to use in order to render that item.

Having exposed the 'has' function for myself, if a record's templateId is not undefined, I check to see if the template has been loaded. If so, I render that template passing the record as the context. If not, I use a default item renderer.

**Comment by RaviRamDhali** [comment]
Can you post code example ?

**Comment by jonnyreeves** [comment]
The unit tests provide examples of the API, but for good measure:

```
$.Mustache.add('added_template', 'a');
console.log($.Mustache.has("non_existent")); // => false
console.log($.Mustache.has("added_template")); // => true
```
