### ISSUE TITLE
Failed to locate Mustache instance, are you sure it has been loaded?

### ISSUE THREAD

**Issue by vacosk** [jonnyreeves/jquery-Mustache#25]
Sorry for all the n00b comments...

I have some simple code that looks like this:

$(document).ready(function(){
    $.Mustache.load('templates.html', function(){
        console.log('templates loaded');
        init();
    });
});
The load works, and if I add a console.log in the add method I can see that my templates have been found correctly in the HTML template file.

However, when I later run $('#my-id').mustache('my-template', {}) I get an error in the JS console:

Uncaught Error: Failed to locate Mustache instance, are you sure it has been loaded?
From what I can see, this is occurring because getMustache is looking for window.Mustache but it looks like that's never set. Should it instead be $.Mustache?

I'm not completely sure what I'm doing here, so this might be pilot error...

**Comment by jonnyreeves** [comment]
Are you including mustache.js on your page as well as jQuery and
jQuery-Mustache? You must have all three scripts present.

**Comment by vacosk** [comment]
Thank you,

that was the problem.
