### ISSUE TITLE
html is rendered as text

### ISSUE THREAD

**Issue by PeterSloth** [jonnyreeves/jquery-Mustache#26]
Hi

I use the code below to render mark-up for my Preview element.

$('#Preview).mustache('my-template', viewData, { method: 'html' });

The viewData contains fields that contain raw text as well as fields which contain html markup. The problem is that the html markup is not rendered, so instead of showing for instance Hello World in bold the Preview element shows &lt;b&gt;Hello World&lt;/b&gt;
Is this a bug or am I doing something wrong?

Thanks
Peter

**Comment by jonnyreeves** [comment]
Hi Peter,

Could you provide a complete example which includes your template markup
and the viewData object in order for me to help you with this issue?

Thanks

**Comment by PeterSloth** [comment]
Hi John

I tried to include the sample on the web site, but a lot markup was removed which made it unreadable, so I here it is:

```
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title></title>
    <script type="text/javascript" src="resources/scripts/jquery-1.8.3.min.js"></script>
    <script type="text/javascript" src="resources/scripts/mustache.js"></script>
    <script type="text/javascript" src="resources/scripts/jquery.mustache.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            var viewData = { name: '<b>Jonny</b>' };
            $.Mustache.add('my-template', '<p>Hi, {{name}}, this is an inline template<p>');
            $('#Preview').mustache('my-template', viewData, { method: 'html' });
        });
    </script>
</head>
<body>
    <div id="Preview"></div>
</body>
</html>
```

**Comment by jonnyreeves** [comment]
mustache.js automatically HTML-escapes all tags wrapped in `{{ }}`'s.  If you don't want mustache.js to HTML-escaped then you need to use either triple mustaches (`{{{name}}}`) or an ampersand in front the variable name `{{&name}}`

So your code should be changed to read:

```
$.Mustache.add('my-template', '<p>Hi, {{{name}}}, this is an inline template with HTML Markup<p>');
```
