### ISSUE TITLE
jquery-Mustache and requireJS (AMD)

### ISSUE THREAD

**Issue by Kitof** [jonnyreeves/jquery-Mustache#37]
Since few months mustache.js have a specific jQuery wrapper. But it focuses on wrapping Mustache.render(). jquery-Mustache seems to have a much broader scope (especially $.Mustache.load that I used to preload templates).

So i tried to add jquery-mustache in my requireJS config, but i'm not able to have a correct configuration.

```
require.config({
    baseUrl: 'js/libs',
    urlArgs: "c=" + (new Date()).getTime(),
    shim: {
        'jquery-mustache': {
            deps: ['jquery', 'mustache']
        }
    },
    paths: {
      'jquery': "jquery/dist/jquery",
      'mustache': "mustache/mustache",
      'jquery-mustache': "jquery-Mustache/jquery.mustache",
      'requirejs': "requirejs/require"
    }
});
```

But jquery-Mustache doesn't find `window.Mustache` object

Do you have any clue ?

**Comment by jonnyreeves** [comment]
Sounds like mustache is not exporting to the global (`window`) object; probably due to the presence of requireJS.  I'm afraid I'm not a big AMD/requireJS user myself, preferring CommonJS/Browserify.

Good luck.
