### ISSUE TITLE
'load' does not work if there is only one 'script' tag

### ISSUE THREAD

**Issue by fddayan** [jonnyreeves/jquery-Mustache#6]
It looks like if the template has only one script tag with a template it does not load the template. 

I think it's because it load the content of the script but not the tag itself with the content and the filter("script") does not work. 

One solution (or hack) would be to ask check tagName in the data received. If it's 'undefined' then it's only one tag.

**Comment by jonnyreeves** [comment]
Hi fddayan, thanks for your interest in jQuery-Mustache!

I tried to reproduce your issue, but external files which only define a single template load fine for me via `$.Mustache.load`.  I have added an example of this in the `examples` folder.

Please let me know if you can still reproduce this issue and hopefully we can resolve it :)

Regards
