### ISSUE TITLE
Add AMD support

### ISSUE THREAD

**Issue by rfromi** [jonnyreeves/jquery-Mustache#7]
I'm using RequireJS it works fine with Mustache and JQuery (latest versions), but not with jquery-Mustache. Can you add support for AMD ?

**Comment by jonnyreeves** [comment]
Hi rfromi, thanks for your interest in jQuery Mustache.

At present I have no plans to directly add a RequireJS module export to jQuery-Mustache however I have added an example of how to use jQuery-Mustache with requireJS by using the RequireJS's `shim` configuration option.

I'll close this issue for now, but if others feel strongly about RequireJS integration then I will consider it in a future release.

All the best!

**Comment by leegee** [comment]
AMD support would be really helpful. Mustache offers it, and so does jQuery.... :)
