### ISSUE TITLE
Conflict in comment in src / jquery-Mustache.js

### ISSUE THREAD

**Issue by terrycojones** [jonnyreeves/jquery-Mustache#9]
There's a git conflict marker in the comment at the top of `src / jquery-Mustache.js`.

**Comment by jonnyreeves** [comment]
Crikey!  Sorry about that.  It's about time I got a grunt script setup to lint and run the unit tests ;)  I'll keep this issue open until that's sorted.

Thanks for letting me know!

**Comment by jonnyreeves** [comment]
Oh, it was actually in the comment - not sure jsHint is quite advanced enough to pick that one up ;).  I'll close this issue and open a new one about a build script.

Thanks again.
